// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pipeline_top_clock_cycle (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        MEM_WB_valid_i,
        MEM_WB_valid_o,
        MEM_WB_valid_o_ap_vld,
        MEM_WB_dest_i,
        MEM_WB_dest_o,
        MEM_WB_dest_o_ap_vld,
        MEM_WB_outVal_V_i,
        MEM_WB_outVal_V_o,
        MEM_WB_outVal_V_o_ap_vld,
        EX_MEM_valid_i,
        EX_MEM_valid_o,
        EX_MEM_valid_o_ap_vld,
        EX_MEM_dest_i,
        EX_MEM_dest_o,
        EX_MEM_dest_o_ap_vld,
        EX_MEM_outVal_V_i,
        EX_MEM_outVal_V_o,
        EX_MEM_outVal_V_o_ap_vld,
        ID_EX_valid_i,
        ID_EX_valid_o,
        ID_EX_valid_o_ap_vld,
        ID_EX_src1_i,
        ID_EX_src1_o,
        ID_EX_src1_o_ap_vld,
        ID_EX_src2_i,
        ID_EX_src2_o,
        ID_EX_src2_o_ap_vld,
        ID_EX_dest_i,
        ID_EX_dest_o,
        ID_EX_dest_o_ap_vld,
        PC_V_i,
        PC_V_o,
        PC_V_o_ap_vld,
        IF_ID_valid_i,
        IF_ID_valid_o,
        IF_ID_valid_o_ap_vld,
        IF_ID_pc_V_i,
        IF_ID_pc_V_o,
        IF_ID_pc_V_o_ap_vld,
        ID_EX_pc_V,
        ID_EX_pc_V_ap_vld,
        ID_EX_val1_V,
        ID_EX_val1_V_ap_vld,
        forward_B_sel_1,
        forward_B_sel_1_ap_vld,
        forward_A_sel_1,
        forward_A_sel_1_ap_vld
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] MEM_WB_valid_i;
output  [0:0] MEM_WB_valid_o;
output   MEM_WB_valid_o_ap_vld;
input  [1:0] MEM_WB_dest_i;
output  [1:0] MEM_WB_dest_o;
output   MEM_WB_dest_o_ap_vld;
input  [0:0] MEM_WB_outVal_V_i;
output  [0:0] MEM_WB_outVal_V_o;
output   MEM_WB_outVal_V_o_ap_vld;
input  [0:0] EX_MEM_valid_i;
output  [0:0] EX_MEM_valid_o;
output   EX_MEM_valid_o_ap_vld;
input  [1:0] EX_MEM_dest_i;
output  [1:0] EX_MEM_dest_o;
output   EX_MEM_dest_o_ap_vld;
input  [0:0] EX_MEM_outVal_V_i;
output  [0:0] EX_MEM_outVal_V_o;
output   EX_MEM_outVal_V_o_ap_vld;
input  [0:0] ID_EX_valid_i;
output  [0:0] ID_EX_valid_o;
output   ID_EX_valid_o_ap_vld;
input  [1:0] ID_EX_src1_i;
output  [1:0] ID_EX_src1_o;
output   ID_EX_src1_o_ap_vld;
input  [1:0] ID_EX_src2_i;
output  [1:0] ID_EX_src2_o;
output   ID_EX_src2_o_ap_vld;
input  [1:0] ID_EX_dest_i;
output  [1:0] ID_EX_dest_o;
output   ID_EX_dest_o_ap_vld;
input  [31:0] PC_V_i;
output  [31:0] PC_V_o;
output   PC_V_o_ap_vld;
input  [0:0] IF_ID_valid_i;
output  [0:0] IF_ID_valid_o;
output   IF_ID_valid_o_ap_vld;
input  [31:0] IF_ID_pc_V_i;
output  [31:0] IF_ID_pc_V_o;
output   IF_ID_pc_V_o_ap_vld;
output  [31:0] ID_EX_pc_V;
output   ID_EX_pc_V_ap_vld;
output  [0:0] ID_EX_val1_V;
output   ID_EX_val1_V_ap_vld;
output  [1:0] forward_B_sel_1;
output   forward_B_sel_1_ap_vld;
output  [1:0] forward_A_sel_1;
output   forward_A_sel_1_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] MEM_WB_valid_o;
reg MEM_WB_valid_o_ap_vld;
reg[1:0] MEM_WB_dest_o;
reg MEM_WB_dest_o_ap_vld;
reg[0:0] MEM_WB_outVal_V_o;
reg MEM_WB_outVal_V_o_ap_vld;
reg[0:0] EX_MEM_valid_o;
reg EX_MEM_valid_o_ap_vld;
reg[1:0] EX_MEM_dest_o;
reg EX_MEM_dest_o_ap_vld;
reg[0:0] EX_MEM_outVal_V_o;
reg EX_MEM_outVal_V_o_ap_vld;
reg[0:0] ID_EX_valid_o;
reg ID_EX_valid_o_ap_vld;
reg[1:0] ID_EX_src1_o;
reg ID_EX_src1_o_ap_vld;
reg[1:0] ID_EX_src2_o;
reg ID_EX_src2_o_ap_vld;
reg[1:0] ID_EX_dest_o;
reg ID_EX_dest_o_ap_vld;
reg[31:0] PC_V_o;
reg PC_V_o_ap_vld;
reg[0:0] IF_ID_valid_o;
reg IF_ID_valid_o_ap_vld;
reg[31:0] IF_ID_pc_V_o;
reg IF_ID_pc_V_o_ap_vld;
reg ID_EX_pc_V_ap_vld;
reg ID_EX_val1_V_ap_vld;
reg forward_B_sel_1_ap_vld;
reg forward_A_sel_1_ap_vld;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [4:0] RegisterFile_V_address0;
reg    RegisterFile_V_ce0;
reg    RegisterFile_V_we0;
wire   [0:0] RegisterFile_V_q0;
wire   [0:0] IF_ID_valid_load_load_fu_235_p1;
reg   [0:0] IF_ID_valid_load_reg_567;
reg   [1:0] ap_phi_mux_forward_A_sel_1_new_4_phi_fu_81_p4;
wire   [0:0] ID_EX_valid_load_load_fu_197_p1;
wire   [1:0] select_ln65_2_fu_433_p3;
reg   [1:0] ap_phi_mux_forward_B_sel_1_new_1_phi_fu_91_p4;
wire   [1:0] select_ln65_4_fu_456_p3;
reg   [31:0] ap_phi_mux_storemerge18_phi_fu_102_p4;
reg   [31:0] storemerge18_reg_98;
wire    ap_CS_fsm_state3;
reg   [0:0] ap_phi_mux_storemerge13_phi_fu_113_p4;
reg   [0:0] storemerge13_reg_109;
reg   [0:0] ap_phi_mux_storemerge9_phi_fu_125_p4;
reg   [0:0] storemerge9_reg_121;
wire  signed [63:0] sext_ln32_fu_168_p1;
wire   [0:0] wb_stage_instr_valid_load_fu_133_p1;
wire   [0:0] or_ln25_fu_162_p2;
wire   [1:0] select_ln41_fu_495_p3;
wire   [31:0] add_ln291_fu_533_p2;
wire    ap_CS_fsm_state2;
wire  signed [1:0] sext_ln25_fu_141_p0;
wire  signed [1:0] icmp_ln25_fu_150_p0;
wire  signed [1:0] icmp_ln25_1_fu_156_p0;
wire   [0:0] icmp_ln25_1_fu_156_p2;
wire   [0:0] icmp_ln25_fu_150_p2;
wire  signed [1:0] sext_ln32_fu_168_p0;
wire  signed [2:0] sext_ln25_fu_141_p1;
wire   [2:0] add_ln69_fu_249_p2;
wire   [1:0] tmp_fu_255_p4;
wire   [0:0] icmp_ln69_fu_265_p2;
wire  signed [1:0] icmp_ln69_1_fu_277_p0;
wire   [0:0] and_ln69_fu_271_p2;
wire   [0:0] icmp_ln69_1_fu_277_p2;
wire   [0:0] and_ln69_1_fu_283_p2;
wire   [0:0] icmp_ln65_1_fu_297_p2;
wire   [0:0] icmp_ln65_2_fu_303_p2;
wire   [0:0] icmp_ln65_fu_243_p2;
wire   [0:0] and_ln65_1_fu_315_p2;
wire   [0:0] and_ln65_fu_309_p2;
wire   [0:0] and_ln65_2_fu_321_p2;
wire   [1:0] select_ln69_fu_289_p3;
wire   [0:0] icmp_ln65_3_fu_341_p2;
wire   [0:0] xor_ln37_fu_353_p2;
wire   [0:0] icmp_ln65_4_fu_347_p2;
wire   [0:0] xor_ln65_fu_359_p2;
wire   [0:0] or_ln65_1_fu_371_p2;
wire   [0:0] or_ln65_fu_365_p2;
wire   [0:0] or_ln65_2_fu_377_p2;
wire   [0:0] and_ln65_3_fu_383_p2;
wire   [1:0] select_ln65_fu_327_p3;
wire  signed [1:0] icmp_ln80_fu_397_p0;
wire   [0:0] icmp_ln80_fu_397_p2;
wire   [0:0] icmp_ln76_fu_335_p2;
wire   [0:0] or_ln65_3_fu_409_p2;
wire   [0:0] and_ln65_5_fu_421_p2;
wire   [0:0] and_ln65_4_fu_415_p2;
wire   [0:0] and_ln65_6_fu_427_p2;
wire   [1:0] select_ln65_1_fu_389_p3;
wire   [0:0] and_ln80_fu_403_p2;
wire   [0:0] or_ln65_4_fu_450_p2;
wire   [1:0] select_ln65_3_fu_442_p3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
end

pipeline_top_clock_cycle_RegisterFile_V_RAM_AUTO_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
RegisterFile_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RegisterFile_V_address0),
    .ce0(RegisterFile_V_ce0),
    .we0(RegisterFile_V_we0),
    .d0(MEM_WB_outVal_V_i),
    .q0(RegisterFile_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'd0 == IF_ID_valid_load_load_fu_235_p1) & (1'b1 == ap_CS_fsm_state1))) begin
        storemerge13_reg_109 <= 1'd1;
    end else if (((1'd1 == IF_ID_valid_load_reg_567) & (1'b1 == ap_CS_fsm_state3))) begin
        storemerge13_reg_109 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'd0 == IF_ID_valid_load_load_fu_235_p1) & (1'b1 == ap_CS_fsm_state1))) begin
        storemerge18_reg_98 <= 32'd0;
    end else if (((1'd1 == IF_ID_valid_load_reg_567) & (1'b1 == ap_CS_fsm_state3))) begin
        storemerge18_reg_98 <= IF_ID_pc_V_i;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'd0 == IF_ID_valid_load_load_fu_235_p1) & (1'b1 == ap_CS_fsm_state1))) begin
        storemerge9_reg_121 <= 1'd0;
    end else if (((1'd1 == IF_ID_valid_load_reg_567) & (1'b1 == ap_CS_fsm_state3))) begin
        storemerge9_reg_121 <= RegisterFile_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        IF_ID_valid_load_reg_567 <= IF_ID_valid_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        EX_MEM_dest_o = ID_EX_dest_i;
    end else begin
        EX_MEM_dest_o = EX_MEM_dest_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        EX_MEM_dest_o_ap_vld = 1'b1;
    end else begin
        EX_MEM_dest_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        EX_MEM_outVal_V_o = 1'd0;
    end else begin
        EX_MEM_outVal_V_o = EX_MEM_outVal_V_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        EX_MEM_outVal_V_o_ap_vld = 1'b1;
    end else begin
        EX_MEM_outVal_V_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        EX_MEM_valid_o = ID_EX_valid_i;
    end else begin
        EX_MEM_valid_o = EX_MEM_valid_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        EX_MEM_valid_o_ap_vld = 1'b1;
    end else begin
        EX_MEM_valid_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ID_EX_dest_o = 2'd3;
    end else begin
        ID_EX_dest_o = ID_EX_dest_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ID_EX_dest_o_ap_vld = 1'b1;
    end else begin
        ID_EX_dest_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ID_EX_pc_V_ap_vld = 1'b1;
    end else begin
        ID_EX_pc_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ID_EX_src1_o = select_ln41_fu_495_p3;
    end else begin
        ID_EX_src1_o = ID_EX_src1_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ID_EX_src1_o_ap_vld = 1'b1;
    end else begin
        ID_EX_src1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ID_EX_src2_o = 2'd3;
    end else begin
        ID_EX_src2_o = ID_EX_src2_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ID_EX_src2_o_ap_vld = 1'b1;
    end else begin
        ID_EX_src2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ID_EX_val1_V_ap_vld = 1'b1;
    end else begin
        ID_EX_val1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'd0 == IF_ID_valid_load_load_fu_235_p1) & (1'b1 == ap_CS_fsm_state1))) begin
        ID_EX_valid_o = 1'd0;
    end else if (((1'd1 == IF_ID_valid_load_reg_567) & (1'b1 == ap_CS_fsm_state3))) begin
        ID_EX_valid_o = 1'd1;
    end else begin
        ID_EX_valid_o = ID_EX_valid_i;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b1) & (1'd0 == IF_ID_valid_load_load_fu_235_p1) & (1'b1 == ap_CS_fsm_state1)) | ((1'd1 == IF_ID_valid_load_reg_567) & (1'b1 == ap_CS_fsm_state3)))) begin
        ID_EX_valid_o_ap_vld = 1'b1;
    end else begin
        ID_EX_valid_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        IF_ID_pc_V_o = PC_V_i;
    end else begin
        IF_ID_pc_V_o = IF_ID_pc_V_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        IF_ID_pc_V_o_ap_vld = 1'b1;
    end else begin
        IF_ID_pc_V_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        IF_ID_valid_o = 1'd1;
    end else begin
        IF_ID_valid_o = IF_ID_valid_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        IF_ID_valid_o_ap_vld = 1'b1;
    end else begin
        IF_ID_valid_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        MEM_WB_dest_o = EX_MEM_dest_i;
    end else begin
        MEM_WB_dest_o = MEM_WB_dest_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        MEM_WB_dest_o_ap_vld = 1'b1;
    end else begin
        MEM_WB_dest_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        MEM_WB_outVal_V_o = EX_MEM_outVal_V_i;
    end else begin
        MEM_WB_outVal_V_o = MEM_WB_outVal_V_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        MEM_WB_outVal_V_o_ap_vld = 1'b1;
    end else begin
        MEM_WB_outVal_V_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        MEM_WB_valid_o = EX_MEM_valid_i;
    end else begin
        MEM_WB_valid_o = MEM_WB_valid_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        MEM_WB_valid_o_ap_vld = 1'b1;
    end else begin
        MEM_WB_valid_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        PC_V_o = add_ln291_fu_533_p2;
    end else begin
        PC_V_o = PC_V_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        PC_V_o_ap_vld = 1'b1;
    end else begin
        PC_V_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        RegisterFile_V_address0 = 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        RegisterFile_V_address0 = sext_ln32_fu_168_p1;
    end else begin
        RegisterFile_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        RegisterFile_V_ce0 = 1'b1;
    end else begin
        RegisterFile_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (or_ln25_fu_162_p2 == 1'd0) & (wb_stage_instr_valid_load_fu_133_p1 == 1'd1))) begin
        RegisterFile_V_we0 = 1'b1;
    end else begin
        RegisterFile_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd1 == ID_EX_valid_load_load_fu_197_p1)) begin
            ap_phi_mux_forward_A_sel_1_new_4_phi_fu_81_p4 = select_ln65_2_fu_433_p3;
        end else if ((1'd0 == ID_EX_valid_load_load_fu_197_p1)) begin
            ap_phi_mux_forward_A_sel_1_new_4_phi_fu_81_p4 = 2'd0;
        end else begin
            ap_phi_mux_forward_A_sel_1_new_4_phi_fu_81_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_forward_A_sel_1_new_4_phi_fu_81_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'd1 == ID_EX_valid_load_load_fu_197_p1)) begin
            ap_phi_mux_forward_B_sel_1_new_1_phi_fu_91_p4 = select_ln65_4_fu_456_p3;
        end else if ((1'd0 == ID_EX_valid_load_load_fu_197_p1)) begin
            ap_phi_mux_forward_B_sel_1_new_1_phi_fu_91_p4 = 2'd0;
        end else begin
            ap_phi_mux_forward_B_sel_1_new_1_phi_fu_91_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_forward_B_sel_1_new_1_phi_fu_91_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'd1 == IF_ID_valid_load_reg_567) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_phi_mux_storemerge13_phi_fu_113_p4 = 1'd0;
    end else begin
        ap_phi_mux_storemerge13_phi_fu_113_p4 = storemerge13_reg_109;
    end
end

always @ (*) begin
    if (((1'd1 == IF_ID_valid_load_reg_567) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_phi_mux_storemerge18_phi_fu_102_p4 = IF_ID_pc_V_i;
    end else begin
        ap_phi_mux_storemerge18_phi_fu_102_p4 = storemerge18_reg_98;
    end
end

always @ (*) begin
    if (((1'd1 == IF_ID_valid_load_reg_567) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_phi_mux_storemerge9_phi_fu_125_p4 = RegisterFile_V_q0;
    end else begin
        ap_phi_mux_storemerge9_phi_fu_125_p4 = storemerge9_reg_121;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        forward_A_sel_1_ap_vld = 1'b1;
    end else begin
        forward_A_sel_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        forward_B_sel_1_ap_vld = 1'b1;
    end else begin
        forward_B_sel_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'd0 == IF_ID_valid_load_load_fu_235_p1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((1'd1 == IF_ID_valid_load_load_fu_235_p1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ID_EX_pc_V = ap_phi_mux_storemerge18_phi_fu_102_p4;

assign ID_EX_val1_V = ap_phi_mux_storemerge9_phi_fu_125_p4;

assign ID_EX_valid_load_load_fu_197_p1 = ID_EX_valid_i;

assign IF_ID_valid_load_load_fu_235_p1 = IF_ID_valid_i;

assign add_ln291_fu_533_p2 = (PC_V_i + 32'd4);

assign add_ln69_fu_249_p2 = ($signed(sext_ln25_fu_141_p1) + $signed(3'd1));

assign and_ln65_1_fu_315_p2 = (icmp_ln65_fu_243_p2 & icmp_ln65_2_fu_303_p2);

assign and_ln65_2_fu_321_p2 = (and_ln65_fu_309_p2 & and_ln65_1_fu_315_p2);

assign and_ln65_3_fu_383_p2 = (xor_ln37_fu_353_p2 & or_ln65_2_fu_377_p2);

assign and_ln65_4_fu_415_p2 = (icmp_ln76_fu_335_p2 & icmp_ln65_2_fu_303_p2);

assign and_ln65_5_fu_421_p2 = (or_ln65_3_fu_409_p2 & icmp_ln65_1_fu_297_p2);

assign and_ln65_6_fu_427_p2 = (and_ln65_5_fu_421_p2 & and_ln65_4_fu_415_p2);

assign and_ln65_fu_309_p2 = (icmp_ln65_1_fu_297_p2 & EX_MEM_valid_i);

assign and_ln69_1_fu_283_p2 = (icmp_ln69_1_fu_277_p2 & and_ln69_fu_271_p2);

assign and_ln69_fu_271_p2 = (icmp_ln69_fu_265_p2 & MEM_WB_valid_i);

assign and_ln80_fu_403_p2 = (icmp_ln80_fu_397_p2 & and_ln69_fu_271_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign forward_A_sel_1 = ap_phi_mux_forward_A_sel_1_new_4_phi_fu_81_p4;

assign forward_B_sel_1 = ap_phi_mux_forward_B_sel_1_new_1_phi_fu_91_p4;

assign icmp_ln25_1_fu_156_p0 = MEM_WB_dest_i;

assign icmp_ln25_1_fu_156_p2 = ((icmp_ln25_1_fu_156_p0 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_150_p0 = MEM_WB_dest_i;

assign icmp_ln25_fu_150_p2 = ((icmp_ln25_fu_150_p0 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln65_1_fu_297_p2 = ((EX_MEM_dest_i != 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln65_2_fu_303_p2 = ((EX_MEM_dest_i != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln65_3_fu_341_p2 = ((EX_MEM_dest_i == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln65_4_fu_347_p2 = ((EX_MEM_dest_i == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_243_p2 = ((EX_MEM_dest_i == ID_EX_src1_i) ? 1'b1 : 1'b0);

assign icmp_ln69_1_fu_277_p0 = MEM_WB_dest_i;

assign icmp_ln69_1_fu_277_p2 = ((icmp_ln69_1_fu_277_p0 == ID_EX_src1_i) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_265_p2 = ((tmp_fu_255_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_335_p2 = ((EX_MEM_dest_i == ID_EX_src2_i) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_397_p0 = MEM_WB_dest_i;

assign icmp_ln80_fu_397_p2 = ((icmp_ln80_fu_397_p0 == ID_EX_src2_i) ? 1'b1 : 1'b0);

assign or_ln25_fu_162_p2 = (icmp_ln25_fu_150_p2 | icmp_ln25_1_fu_156_p2);

assign or_ln65_1_fu_371_p2 = (xor_ln65_fu_359_p2 | icmp_ln65_4_fu_347_p2);

assign or_ln65_2_fu_377_p2 = (or_ln65_fu_365_p2 | or_ln65_1_fu_371_p2);

assign or_ln65_3_fu_409_p2 = (and_ln65_2_fu_321_p2 | EX_MEM_valid_i);

assign or_ln65_4_fu_450_p2 = (and_ln80_fu_403_p2 | and_ln65_6_fu_427_p2);

assign or_ln65_fu_365_p2 = (xor_ln37_fu_353_p2 | icmp_ln65_3_fu_341_p2);

assign select_ln41_fu_495_p3 = ((ap_phi_mux_storemerge13_phi_fu_113_p4[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign select_ln65_1_fu_389_p3 = ((and_ln65_3_fu_383_p2[0:0] == 1'b1) ? select_ln69_fu_289_p3 : select_ln65_fu_327_p3);

assign select_ln65_2_fu_433_p3 = ((and_ln65_6_fu_427_p2[0:0] == 1'b1) ? select_ln65_fu_327_p3 : select_ln65_1_fu_389_p3);

assign select_ln65_3_fu_442_p3 = ((and_ln65_6_fu_427_p2[0:0] == 1'b1) ? 2'd1 : 2'd2);

assign select_ln65_4_fu_456_p3 = ((or_ln65_4_fu_450_p2[0:0] == 1'b1) ? select_ln65_3_fu_442_p3 : 2'd0);

assign select_ln65_fu_327_p3 = ((and_ln65_2_fu_321_p2[0:0] == 1'b1) ? 2'd1 : select_ln69_fu_289_p3);

assign select_ln69_fu_289_p3 = ((and_ln69_1_fu_283_p2[0:0] == 1'b1) ? 2'd2 : 2'd0);

assign sext_ln25_fu_141_p0 = MEM_WB_dest_i;

assign sext_ln25_fu_141_p1 = sext_ln25_fu_141_p0;

assign sext_ln32_fu_168_p0 = MEM_WB_dest_i;

assign sext_ln32_fu_168_p1 = sext_ln32_fu_168_p0;

assign tmp_fu_255_p4 = {{add_ln69_fu_249_p2[2:1]}};

assign wb_stage_instr_valid_load_fu_133_p1 = MEM_WB_valid_i;

assign xor_ln37_fu_353_p2 = (1'd1 ^ EX_MEM_valid_i);

assign xor_ln65_fu_359_p2 = (icmp_ln65_fu_243_p2 ^ 1'd1);

endmodule //pipeline_top_clock_cycle
