# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/sreer/Post-Silicon-Validation-Research-Project/new_cpu_implementation/vivado/PSV_IMP/PSV_IMP.srcs/sources_1/bd/design_1/ip/design_1_pipeline_top_0_0/design_1_pipeline_top_0_0.xci
# IP: The module: 'design_1_pipeline_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sreer/Post-Silicon-Validation-Research-Project/new_cpu_implementation/vivado/PSV_IMP/PSV_IMP.gen/sources_1/bd/design_1/ip/design_1_pipeline_top_0_0/constraints/pipeline_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_pipeline_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/sreer/Post-Silicon-Validation-Research-Project/new_cpu_implementation/vivado/PSV_IMP/PSV_IMP.srcs/sources_1/bd/design_1/ip/design_1_pipeline_top_0_0/design_1_pipeline_top_0_0.xci
# IP: The module: 'design_1_pipeline_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sreer/Post-Silicon-Validation-Research-Project/new_cpu_implementation/vivado/PSV_IMP/PSV_IMP.gen/sources_1/bd/design_1/ip/design_1_pipeline_top_0_0/constraints/pipeline_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_pipeline_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
