-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pipeline_top is
port (
    ap_local_block : OUT STD_LOGIC;
    ap_local_deadlock : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    reset : IN STD_LOGIC;
    stall_out : OUT STD_LOGIC;
    forward_A_sel_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    forward_B_sel_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    hazard_dest_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    pc_out : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of pipeline_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "pipeline_top_pipeline_top,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k70t-fbv676-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.154000,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=128,HLS_SYN_LUT=637,HLS_VERSION=2021_2}";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal IF_ID_valid : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal IF_ID_pc_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ID_EX_valid : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ID_EX_src1 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ID_EX_src2 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ID_EX_dest : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal EX_MEM_valid : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal EX_MEM_dest : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal EX_MEM_outVal_V : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal MEM_WB_valid : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal MEM_WB_dest : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal MEM_WB_outVal_V : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal forward_A_sel_1 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal forward_B_sel_1 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal PC_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_clock_cycle_fu_123_ap_start : STD_LOGIC;
    signal grp_clock_cycle_fu_123_ap_done : STD_LOGIC;
    signal grp_clock_cycle_fu_123_ap_idle : STD_LOGIC;
    signal grp_clock_cycle_fu_123_ap_ready : STD_LOGIC;
    signal grp_clock_cycle_fu_123_MEM_WB_valid_o : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_clock_cycle_fu_123_MEM_WB_valid_o_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_MEM_WB_dest_o : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_clock_cycle_fu_123_MEM_WB_dest_o_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_MEM_WB_outVal_V_o : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_clock_cycle_fu_123_MEM_WB_outVal_V_o_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_EX_MEM_valid_o : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_clock_cycle_fu_123_EX_MEM_valid_o_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_EX_MEM_dest_o : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_clock_cycle_fu_123_EX_MEM_dest_o_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_EX_MEM_outVal_V_o : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_clock_cycle_fu_123_EX_MEM_outVal_V_o_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_ID_EX_valid_o : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_clock_cycle_fu_123_ID_EX_valid_o_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_ID_EX_src1_o : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_clock_cycle_fu_123_ID_EX_src1_o_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_ID_EX_src2_o : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_clock_cycle_fu_123_ID_EX_src2_o_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_ID_EX_dest_o : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_clock_cycle_fu_123_ID_EX_dest_o_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_PC_V_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_clock_cycle_fu_123_PC_V_o_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_IF_ID_valid_o : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_clock_cycle_fu_123_IF_ID_valid_o_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_IF_ID_pc_V_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_clock_cycle_fu_123_IF_ID_pc_V_o_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_ID_EX_pc_V : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_clock_cycle_fu_123_ID_EX_pc_V_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_ID_EX_val1_V : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_clock_cycle_fu_123_ID_EX_val1_V_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_forward_B_sel_1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_clock_cycle_fu_123_forward_B_sel_1_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_forward_A_sel_1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_clock_cycle_fu_123_forward_A_sel_1_ap_vld : STD_LOGIC;
    signal grp_clock_cycle_fu_123_ap_start_reg : STD_LOGIC := '0';
    signal reset_read_read_fu_80_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pipeline_top_clock_cycle IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        MEM_WB_valid_i : IN STD_LOGIC_VECTOR (0 downto 0);
        MEM_WB_valid_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        MEM_WB_valid_o_ap_vld : OUT STD_LOGIC;
        MEM_WB_dest_i : IN STD_LOGIC_VECTOR (1 downto 0);
        MEM_WB_dest_o : OUT STD_LOGIC_VECTOR (1 downto 0);
        MEM_WB_dest_o_ap_vld : OUT STD_LOGIC;
        MEM_WB_outVal_V_i : IN STD_LOGIC_VECTOR (0 downto 0);
        MEM_WB_outVal_V_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        MEM_WB_outVal_V_o_ap_vld : OUT STD_LOGIC;
        EX_MEM_valid_i : IN STD_LOGIC_VECTOR (0 downto 0);
        EX_MEM_valid_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        EX_MEM_valid_o_ap_vld : OUT STD_LOGIC;
        EX_MEM_dest_i : IN STD_LOGIC_VECTOR (1 downto 0);
        EX_MEM_dest_o : OUT STD_LOGIC_VECTOR (1 downto 0);
        EX_MEM_dest_o_ap_vld : OUT STD_LOGIC;
        EX_MEM_outVal_V_i : IN STD_LOGIC_VECTOR (0 downto 0);
        EX_MEM_outVal_V_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        EX_MEM_outVal_V_o_ap_vld : OUT STD_LOGIC;
        ID_EX_valid_i : IN STD_LOGIC_VECTOR (0 downto 0);
        ID_EX_valid_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        ID_EX_valid_o_ap_vld : OUT STD_LOGIC;
        ID_EX_src1_i : IN STD_LOGIC_VECTOR (1 downto 0);
        ID_EX_src1_o : OUT STD_LOGIC_VECTOR (1 downto 0);
        ID_EX_src1_o_ap_vld : OUT STD_LOGIC;
        ID_EX_src2_i : IN STD_LOGIC_VECTOR (1 downto 0);
        ID_EX_src2_o : OUT STD_LOGIC_VECTOR (1 downto 0);
        ID_EX_src2_o_ap_vld : OUT STD_LOGIC;
        ID_EX_dest_i : IN STD_LOGIC_VECTOR (1 downto 0);
        ID_EX_dest_o : OUT STD_LOGIC_VECTOR (1 downto 0);
        ID_EX_dest_o_ap_vld : OUT STD_LOGIC;
        PC_V_i : IN STD_LOGIC_VECTOR (31 downto 0);
        PC_V_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        PC_V_o_ap_vld : OUT STD_LOGIC;
        IF_ID_valid_i : IN STD_LOGIC_VECTOR (0 downto 0);
        IF_ID_valid_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        IF_ID_valid_o_ap_vld : OUT STD_LOGIC;
        IF_ID_pc_V_i : IN STD_LOGIC_VECTOR (31 downto 0);
        IF_ID_pc_V_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        IF_ID_pc_V_o_ap_vld : OUT STD_LOGIC;
        ID_EX_pc_V : OUT STD_LOGIC_VECTOR (31 downto 0);
        ID_EX_pc_V_ap_vld : OUT STD_LOGIC;
        ID_EX_val1_V : OUT STD_LOGIC_VECTOR (0 downto 0);
        ID_EX_val1_V_ap_vld : OUT STD_LOGIC;
        forward_B_sel_1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        forward_B_sel_1_ap_vld : OUT STD_LOGIC;
        forward_A_sel_1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        forward_A_sel_1_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_clock_cycle_fu_123 : component pipeline_top_clock_cycle
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_clock_cycle_fu_123_ap_start,
        ap_done => grp_clock_cycle_fu_123_ap_done,
        ap_idle => grp_clock_cycle_fu_123_ap_idle,
        ap_ready => grp_clock_cycle_fu_123_ap_ready,
        MEM_WB_valid_i => MEM_WB_valid,
        MEM_WB_valid_o => grp_clock_cycle_fu_123_MEM_WB_valid_o,
        MEM_WB_valid_o_ap_vld => grp_clock_cycle_fu_123_MEM_WB_valid_o_ap_vld,
        MEM_WB_dest_i => MEM_WB_dest,
        MEM_WB_dest_o => grp_clock_cycle_fu_123_MEM_WB_dest_o,
        MEM_WB_dest_o_ap_vld => grp_clock_cycle_fu_123_MEM_WB_dest_o_ap_vld,
        MEM_WB_outVal_V_i => MEM_WB_outVal_V,
        MEM_WB_outVal_V_o => grp_clock_cycle_fu_123_MEM_WB_outVal_V_o,
        MEM_WB_outVal_V_o_ap_vld => grp_clock_cycle_fu_123_MEM_WB_outVal_V_o_ap_vld,
        EX_MEM_valid_i => EX_MEM_valid,
        EX_MEM_valid_o => grp_clock_cycle_fu_123_EX_MEM_valid_o,
        EX_MEM_valid_o_ap_vld => grp_clock_cycle_fu_123_EX_MEM_valid_o_ap_vld,
        EX_MEM_dest_i => EX_MEM_dest,
        EX_MEM_dest_o => grp_clock_cycle_fu_123_EX_MEM_dest_o,
        EX_MEM_dest_o_ap_vld => grp_clock_cycle_fu_123_EX_MEM_dest_o_ap_vld,
        EX_MEM_outVal_V_i => EX_MEM_outVal_V,
        EX_MEM_outVal_V_o => grp_clock_cycle_fu_123_EX_MEM_outVal_V_o,
        EX_MEM_outVal_V_o_ap_vld => grp_clock_cycle_fu_123_EX_MEM_outVal_V_o_ap_vld,
        ID_EX_valid_i => ID_EX_valid,
        ID_EX_valid_o => grp_clock_cycle_fu_123_ID_EX_valid_o,
        ID_EX_valid_o_ap_vld => grp_clock_cycle_fu_123_ID_EX_valid_o_ap_vld,
        ID_EX_src1_i => ID_EX_src1,
        ID_EX_src1_o => grp_clock_cycle_fu_123_ID_EX_src1_o,
        ID_EX_src1_o_ap_vld => grp_clock_cycle_fu_123_ID_EX_src1_o_ap_vld,
        ID_EX_src2_i => ID_EX_src2,
        ID_EX_src2_o => grp_clock_cycle_fu_123_ID_EX_src2_o,
        ID_EX_src2_o_ap_vld => grp_clock_cycle_fu_123_ID_EX_src2_o_ap_vld,
        ID_EX_dest_i => ID_EX_dest,
        ID_EX_dest_o => grp_clock_cycle_fu_123_ID_EX_dest_o,
        ID_EX_dest_o_ap_vld => grp_clock_cycle_fu_123_ID_EX_dest_o_ap_vld,
        PC_V_i => PC_V,
        PC_V_o => grp_clock_cycle_fu_123_PC_V_o,
        PC_V_o_ap_vld => grp_clock_cycle_fu_123_PC_V_o_ap_vld,
        IF_ID_valid_i => IF_ID_valid,
        IF_ID_valid_o => grp_clock_cycle_fu_123_IF_ID_valid_o,
        IF_ID_valid_o_ap_vld => grp_clock_cycle_fu_123_IF_ID_valid_o_ap_vld,
        IF_ID_pc_V_i => IF_ID_pc_V,
        IF_ID_pc_V_o => grp_clock_cycle_fu_123_IF_ID_pc_V_o,
        IF_ID_pc_V_o_ap_vld => grp_clock_cycle_fu_123_IF_ID_pc_V_o_ap_vld,
        ID_EX_pc_V => grp_clock_cycle_fu_123_ID_EX_pc_V,
        ID_EX_pc_V_ap_vld => grp_clock_cycle_fu_123_ID_EX_pc_V_ap_vld,
        ID_EX_val1_V => grp_clock_cycle_fu_123_ID_EX_val1_V,
        ID_EX_val1_V_ap_vld => grp_clock_cycle_fu_123_ID_EX_val1_V_ap_vld,
        forward_B_sel_1 => grp_clock_cycle_fu_123_forward_B_sel_1,
        forward_B_sel_1_ap_vld => grp_clock_cycle_fu_123_forward_B_sel_1_ap_vld,
        forward_A_sel_1 => grp_clock_cycle_fu_123_forward_A_sel_1,
        forward_A_sel_1_ap_vld => grp_clock_cycle_fu_123_forward_A_sel_1_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_clock_cycle_fu_123_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_clock_cycle_fu_123_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_0))) then 
                    grp_clock_cycle_fu_123_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_clock_cycle_fu_123_ap_ready = ap_const_logic_1)) then 
                    grp_clock_cycle_fu_123_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    EX_MEM_dest_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_1))) then 
                EX_MEM_dest <= ap_const_lv2_3;
            elsif (((grp_clock_cycle_fu_123_EX_MEM_dest_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                EX_MEM_dest <= grp_clock_cycle_fu_123_EX_MEM_dest_o;
            end if; 
        end if;
    end process;

    EX_MEM_outVal_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_1))) then 
                EX_MEM_outVal_V <= ap_const_lv1_0;
            elsif (((grp_clock_cycle_fu_123_EX_MEM_outVal_V_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                EX_MEM_outVal_V <= grp_clock_cycle_fu_123_EX_MEM_outVal_V_o;
            end if; 
        end if;
    end process;

    EX_MEM_valid_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_1))) then 
                EX_MEM_valid <= ap_const_lv1_0;
            elsif (((grp_clock_cycle_fu_123_EX_MEM_valid_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                EX_MEM_valid <= grp_clock_cycle_fu_123_EX_MEM_valid_o;
            end if; 
        end if;
    end process;

    ID_EX_dest_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_1))) then 
                ID_EX_dest <= ap_const_lv2_3;
            elsif (((grp_clock_cycle_fu_123_ID_EX_dest_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                ID_EX_dest <= grp_clock_cycle_fu_123_ID_EX_dest_o;
            end if; 
        end if;
    end process;

    ID_EX_src1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_1))) then 
                ID_EX_src1 <= ap_const_lv2_3;
            elsif (((grp_clock_cycle_fu_123_ID_EX_src1_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                ID_EX_src1 <= grp_clock_cycle_fu_123_ID_EX_src1_o;
            end if; 
        end if;
    end process;

    ID_EX_src2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_1))) then 
                ID_EX_src2 <= ap_const_lv2_3;
            elsif (((grp_clock_cycle_fu_123_ID_EX_src2_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                ID_EX_src2 <= grp_clock_cycle_fu_123_ID_EX_src2_o;
            end if; 
        end if;
    end process;

    ID_EX_valid_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_1))) then 
                ID_EX_valid <= ap_const_lv1_0;
            elsif (((grp_clock_cycle_fu_123_ID_EX_valid_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                ID_EX_valid <= grp_clock_cycle_fu_123_ID_EX_valid_o;
            end if; 
        end if;
    end process;

    IF_ID_pc_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_1))) then 
                IF_ID_pc_V <= ap_const_lv32_0;
            elsif (((grp_clock_cycle_fu_123_IF_ID_pc_V_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                IF_ID_pc_V <= grp_clock_cycle_fu_123_IF_ID_pc_V_o;
            end if; 
        end if;
    end process;

    IF_ID_valid_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_1))) then 
                IF_ID_valid <= ap_const_lv1_0;
            elsif (((grp_clock_cycle_fu_123_IF_ID_valid_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                IF_ID_valid <= grp_clock_cycle_fu_123_IF_ID_valid_o;
            end if; 
        end if;
    end process;

    MEM_WB_dest_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_1))) then 
                MEM_WB_dest <= ap_const_lv2_3;
            elsif (((grp_clock_cycle_fu_123_MEM_WB_dest_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                MEM_WB_dest <= grp_clock_cycle_fu_123_MEM_WB_dest_o;
            end if; 
        end if;
    end process;

    MEM_WB_outVal_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_1))) then 
                MEM_WB_outVal_V <= ap_const_lv1_0;
            elsif (((grp_clock_cycle_fu_123_MEM_WB_outVal_V_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                MEM_WB_outVal_V <= grp_clock_cycle_fu_123_MEM_WB_outVal_V_o;
            end if; 
        end if;
    end process;

    MEM_WB_valid_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_1))) then 
                MEM_WB_valid <= ap_const_lv1_0;
            elsif (((grp_clock_cycle_fu_123_MEM_WB_valid_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                MEM_WB_valid <= grp_clock_cycle_fu_123_MEM_WB_valid_o;
            end if; 
        end if;
    end process;

    PC_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_1))) then 
                PC_V <= ap_const_lv32_0;
            elsif (((grp_clock_cycle_fu_123_PC_V_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                PC_V <= grp_clock_cycle_fu_123_PC_V_o;
            end if; 
        end if;
    end process;

    forward_A_sel_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_1))) then 
                forward_A_sel_1 <= ap_const_lv2_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_clock_cycle_fu_123_forward_A_sel_1_ap_vld = ap_const_logic_1))) then 
                forward_A_sel_1 <= grp_clock_cycle_fu_123_forward_A_sel_1;
            end if; 
        end if;
    end process;

    forward_B_sel_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_1))) then 
                forward_B_sel_1 <= ap_const_lv2_0;
            elsif (((grp_clock_cycle_fu_123_forward_B_sel_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                forward_B_sel_1 <= grp_clock_cycle_fu_123_forward_B_sel_1;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_clock_cycle_fu_123_ap_done, reset_read_read_fu_80_p2, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1) and (reset_read_read_fu_80_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_clock_cycle_fu_123_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_clock_cycle_fu_123_ap_done)
    begin
        if ((grp_clock_cycle_fu_123_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_local_block <= ap_const_logic_0;
    ap_local_deadlock <= ap_const_logic_0;

    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    forward_A_sel_out <= std_logic_vector(IEEE.numeric_std.resize(unsigned(forward_A_sel_1),32));
    forward_B_sel_out <= std_logic_vector(IEEE.numeric_std.resize(unsigned(forward_B_sel_1),32));
    grp_clock_cycle_fu_123_ap_start <= grp_clock_cycle_fu_123_ap_start_reg;
    hazard_dest_out <= ap_const_lv32_FFFFFFFF;
    pc_out <= PC_V;
    reset_read_read_fu_80_p2 <= (0=>reset, others=>'-');
    stall_out <= ap_const_logic_0;
end behav;
