// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pipeline_top_pipeline_top,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k70t-fbv676-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.154000,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=128,HLS_SYN_LUT=637,HLS_VERSION=2021_2}" *)

module pipeline_top (
        ap_local_block,
        ap_local_deadlock,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        reset,
        stall_out,
        forward_A_sel_out,
        forward_B_sel_out,
        hazard_dest_out,
        pc_out
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

output   ap_local_block;
output   ap_local_deadlock;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   reset;
output   stall_out;
output  [31:0] forward_A_sel_out;
output  [31:0] forward_B_sel_out;
output  [31:0] hazard_dest_out;
output  [31:0] pc_out;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] IF_ID_valid;
reg   [31:0] IF_ID_pc_V;
reg   [0:0] ID_EX_valid;
reg   [1:0] ID_EX_src1;
reg   [1:0] ID_EX_src2;
reg   [1:0] ID_EX_dest;
reg   [0:0] EX_MEM_valid;
reg   [1:0] EX_MEM_dest;
reg   [0:0] EX_MEM_outVal_V;
reg   [0:0] MEM_WB_valid;
reg   [1:0] MEM_WB_dest;
reg   [0:0] MEM_WB_outVal_V;
reg   [1:0] forward_A_sel_1;
reg   [1:0] forward_B_sel_1;
reg   [31:0] PC_V;
wire    grp_clock_cycle_fu_123_ap_start;
wire    grp_clock_cycle_fu_123_ap_done;
wire    grp_clock_cycle_fu_123_ap_idle;
wire    grp_clock_cycle_fu_123_ap_ready;
wire   [0:0] grp_clock_cycle_fu_123_MEM_WB_valid_o;
wire    grp_clock_cycle_fu_123_MEM_WB_valid_o_ap_vld;
wire   [1:0] grp_clock_cycle_fu_123_MEM_WB_dest_o;
wire    grp_clock_cycle_fu_123_MEM_WB_dest_o_ap_vld;
wire   [0:0] grp_clock_cycle_fu_123_MEM_WB_outVal_V_o;
wire    grp_clock_cycle_fu_123_MEM_WB_outVal_V_o_ap_vld;
wire   [0:0] grp_clock_cycle_fu_123_EX_MEM_valid_o;
wire    grp_clock_cycle_fu_123_EX_MEM_valid_o_ap_vld;
wire   [1:0] grp_clock_cycle_fu_123_EX_MEM_dest_o;
wire    grp_clock_cycle_fu_123_EX_MEM_dest_o_ap_vld;
wire   [0:0] grp_clock_cycle_fu_123_EX_MEM_outVal_V_o;
wire    grp_clock_cycle_fu_123_EX_MEM_outVal_V_o_ap_vld;
wire   [0:0] grp_clock_cycle_fu_123_ID_EX_valid_o;
wire    grp_clock_cycle_fu_123_ID_EX_valid_o_ap_vld;
wire   [1:0] grp_clock_cycle_fu_123_ID_EX_src1_o;
wire    grp_clock_cycle_fu_123_ID_EX_src1_o_ap_vld;
wire   [1:0] grp_clock_cycle_fu_123_ID_EX_src2_o;
wire    grp_clock_cycle_fu_123_ID_EX_src2_o_ap_vld;
wire   [1:0] grp_clock_cycle_fu_123_ID_EX_dest_o;
wire    grp_clock_cycle_fu_123_ID_EX_dest_o_ap_vld;
wire   [31:0] grp_clock_cycle_fu_123_PC_V_o;
wire    grp_clock_cycle_fu_123_PC_V_o_ap_vld;
wire   [0:0] grp_clock_cycle_fu_123_IF_ID_valid_o;
wire    grp_clock_cycle_fu_123_IF_ID_valid_o_ap_vld;
wire   [31:0] grp_clock_cycle_fu_123_IF_ID_pc_V_o;
wire    grp_clock_cycle_fu_123_IF_ID_pc_V_o_ap_vld;
wire   [31:0] grp_clock_cycle_fu_123_ID_EX_pc_V;
wire    grp_clock_cycle_fu_123_ID_EX_pc_V_ap_vld;
wire   [0:0] grp_clock_cycle_fu_123_ID_EX_val1_V;
wire    grp_clock_cycle_fu_123_ID_EX_val1_V_ap_vld;
wire   [1:0] grp_clock_cycle_fu_123_forward_B_sel_1;
wire    grp_clock_cycle_fu_123_forward_B_sel_1_ap_vld;
wire   [1:0] grp_clock_cycle_fu_123_forward_A_sel_1;
wire    grp_clock_cycle_fu_123_forward_A_sel_1_ap_vld;
reg    grp_clock_cycle_fu_123_ap_start_reg;
wire   [0:0] reset_read_read_fu_80_p2;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 IF_ID_valid = 1'd0;
#0 IF_ID_pc_V = 32'd0;
#0 ID_EX_valid = 1'd0;
#0 ID_EX_src1 = 2'd0;
#0 ID_EX_src2 = 2'd0;
#0 ID_EX_dest = 2'd0;
#0 EX_MEM_valid = 1'd0;
#0 EX_MEM_dest = 2'd0;
#0 EX_MEM_outVal_V = 1'd0;
#0 MEM_WB_valid = 1'd0;
#0 MEM_WB_dest = 2'd0;
#0 MEM_WB_outVal_V = 1'd0;
#0 forward_A_sel_1 = 2'd0;
#0 forward_B_sel_1 = 2'd0;
#0 PC_V = 32'd0;
#0 grp_clock_cycle_fu_123_ap_start_reg = 1'b0;
end

pipeline_top_clock_cycle grp_clock_cycle_fu_123(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_clock_cycle_fu_123_ap_start),
    .ap_done(grp_clock_cycle_fu_123_ap_done),
    .ap_idle(grp_clock_cycle_fu_123_ap_idle),
    .ap_ready(grp_clock_cycle_fu_123_ap_ready),
    .MEM_WB_valid_i(MEM_WB_valid),
    .MEM_WB_valid_o(grp_clock_cycle_fu_123_MEM_WB_valid_o),
    .MEM_WB_valid_o_ap_vld(grp_clock_cycle_fu_123_MEM_WB_valid_o_ap_vld),
    .MEM_WB_dest_i(MEM_WB_dest),
    .MEM_WB_dest_o(grp_clock_cycle_fu_123_MEM_WB_dest_o),
    .MEM_WB_dest_o_ap_vld(grp_clock_cycle_fu_123_MEM_WB_dest_o_ap_vld),
    .MEM_WB_outVal_V_i(MEM_WB_outVal_V),
    .MEM_WB_outVal_V_o(grp_clock_cycle_fu_123_MEM_WB_outVal_V_o),
    .MEM_WB_outVal_V_o_ap_vld(grp_clock_cycle_fu_123_MEM_WB_outVal_V_o_ap_vld),
    .EX_MEM_valid_i(EX_MEM_valid),
    .EX_MEM_valid_o(grp_clock_cycle_fu_123_EX_MEM_valid_o),
    .EX_MEM_valid_o_ap_vld(grp_clock_cycle_fu_123_EX_MEM_valid_o_ap_vld),
    .EX_MEM_dest_i(EX_MEM_dest),
    .EX_MEM_dest_o(grp_clock_cycle_fu_123_EX_MEM_dest_o),
    .EX_MEM_dest_o_ap_vld(grp_clock_cycle_fu_123_EX_MEM_dest_o_ap_vld),
    .EX_MEM_outVal_V_i(EX_MEM_outVal_V),
    .EX_MEM_outVal_V_o(grp_clock_cycle_fu_123_EX_MEM_outVal_V_o),
    .EX_MEM_outVal_V_o_ap_vld(grp_clock_cycle_fu_123_EX_MEM_outVal_V_o_ap_vld),
    .ID_EX_valid_i(ID_EX_valid),
    .ID_EX_valid_o(grp_clock_cycle_fu_123_ID_EX_valid_o),
    .ID_EX_valid_o_ap_vld(grp_clock_cycle_fu_123_ID_EX_valid_o_ap_vld),
    .ID_EX_src1_i(ID_EX_src1),
    .ID_EX_src1_o(grp_clock_cycle_fu_123_ID_EX_src1_o),
    .ID_EX_src1_o_ap_vld(grp_clock_cycle_fu_123_ID_EX_src1_o_ap_vld),
    .ID_EX_src2_i(ID_EX_src2),
    .ID_EX_src2_o(grp_clock_cycle_fu_123_ID_EX_src2_o),
    .ID_EX_src2_o_ap_vld(grp_clock_cycle_fu_123_ID_EX_src2_o_ap_vld),
    .ID_EX_dest_i(ID_EX_dest),
    .ID_EX_dest_o(grp_clock_cycle_fu_123_ID_EX_dest_o),
    .ID_EX_dest_o_ap_vld(grp_clock_cycle_fu_123_ID_EX_dest_o_ap_vld),
    .PC_V_i(PC_V),
    .PC_V_o(grp_clock_cycle_fu_123_PC_V_o),
    .PC_V_o_ap_vld(grp_clock_cycle_fu_123_PC_V_o_ap_vld),
    .IF_ID_valid_i(IF_ID_valid),
    .IF_ID_valid_o(grp_clock_cycle_fu_123_IF_ID_valid_o),
    .IF_ID_valid_o_ap_vld(grp_clock_cycle_fu_123_IF_ID_valid_o_ap_vld),
    .IF_ID_pc_V_i(IF_ID_pc_V),
    .IF_ID_pc_V_o(grp_clock_cycle_fu_123_IF_ID_pc_V_o),
    .IF_ID_pc_V_o_ap_vld(grp_clock_cycle_fu_123_IF_ID_pc_V_o_ap_vld),
    .ID_EX_pc_V(grp_clock_cycle_fu_123_ID_EX_pc_V),
    .ID_EX_pc_V_ap_vld(grp_clock_cycle_fu_123_ID_EX_pc_V_ap_vld),
    .ID_EX_val1_V(grp_clock_cycle_fu_123_ID_EX_val1_V),
    .ID_EX_val1_V_ap_vld(grp_clock_cycle_fu_123_ID_EX_val1_V_ap_vld),
    .forward_B_sel_1(grp_clock_cycle_fu_123_forward_B_sel_1),
    .forward_B_sel_1_ap_vld(grp_clock_cycle_fu_123_forward_B_sel_1_ap_vld),
    .forward_A_sel_1(grp_clock_cycle_fu_123_forward_A_sel_1),
    .forward_A_sel_1_ap_vld(grp_clock_cycle_fu_123_forward_A_sel_1_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_clock_cycle_fu_123_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd0))) begin
            grp_clock_cycle_fu_123_ap_start_reg <= 1'b1;
        end else if ((grp_clock_cycle_fu_123_ap_ready == 1'b1)) begin
            grp_clock_cycle_fu_123_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd1))) begin
        EX_MEM_dest <= 2'd3;
    end else if (((grp_clock_cycle_fu_123_EX_MEM_dest_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        EX_MEM_dest <= grp_clock_cycle_fu_123_EX_MEM_dest_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd1))) begin
        EX_MEM_outVal_V <= 1'd0;
    end else if (((grp_clock_cycle_fu_123_EX_MEM_outVal_V_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        EX_MEM_outVal_V <= grp_clock_cycle_fu_123_EX_MEM_outVal_V_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd1))) begin
        EX_MEM_valid <= 1'd0;
    end else if (((grp_clock_cycle_fu_123_EX_MEM_valid_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        EX_MEM_valid <= grp_clock_cycle_fu_123_EX_MEM_valid_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd1))) begin
        ID_EX_dest <= 2'd3;
    end else if (((grp_clock_cycle_fu_123_ID_EX_dest_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ID_EX_dest <= grp_clock_cycle_fu_123_ID_EX_dest_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd1))) begin
        ID_EX_src1 <= 2'd3;
    end else if (((grp_clock_cycle_fu_123_ID_EX_src1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ID_EX_src1 <= grp_clock_cycle_fu_123_ID_EX_src1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd1))) begin
        ID_EX_src2 <= 2'd3;
    end else if (((grp_clock_cycle_fu_123_ID_EX_src2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ID_EX_src2 <= grp_clock_cycle_fu_123_ID_EX_src2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd1))) begin
        ID_EX_valid <= 1'd0;
    end else if (((grp_clock_cycle_fu_123_ID_EX_valid_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ID_EX_valid <= grp_clock_cycle_fu_123_ID_EX_valid_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd1))) begin
        IF_ID_pc_V <= 32'd0;
    end else if (((grp_clock_cycle_fu_123_IF_ID_pc_V_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        IF_ID_pc_V <= grp_clock_cycle_fu_123_IF_ID_pc_V_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd1))) begin
        IF_ID_valid <= 1'd0;
    end else if (((grp_clock_cycle_fu_123_IF_ID_valid_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        IF_ID_valid <= grp_clock_cycle_fu_123_IF_ID_valid_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd1))) begin
        MEM_WB_dest <= 2'd3;
    end else if (((grp_clock_cycle_fu_123_MEM_WB_dest_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        MEM_WB_dest <= grp_clock_cycle_fu_123_MEM_WB_dest_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd1))) begin
        MEM_WB_outVal_V <= 1'd0;
    end else if (((grp_clock_cycle_fu_123_MEM_WB_outVal_V_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        MEM_WB_outVal_V <= grp_clock_cycle_fu_123_MEM_WB_outVal_V_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd1))) begin
        MEM_WB_valid <= 1'd0;
    end else if (((grp_clock_cycle_fu_123_MEM_WB_valid_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        MEM_WB_valid <= grp_clock_cycle_fu_123_MEM_WB_valid_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd1))) begin
        PC_V <= 32'd0;
    end else if (((grp_clock_cycle_fu_123_PC_V_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        PC_V <= grp_clock_cycle_fu_123_PC_V_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd1))) begin
        forward_A_sel_1 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_clock_cycle_fu_123_forward_A_sel_1_ap_vld == 1'b1))) begin
        forward_A_sel_1 <= grp_clock_cycle_fu_123_forward_A_sel_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd1))) begin
        forward_B_sel_1 <= 2'd0;
    end else if (((grp_clock_cycle_fu_123_forward_B_sel_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        forward_B_sel_1 <= grp_clock_cycle_fu_123_forward_B_sel_1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_clock_cycle_fu_123_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & (reset_read_read_fu_80_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_clock_cycle_fu_123_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

assign forward_A_sel_out = forward_A_sel_1;

assign forward_B_sel_out = forward_B_sel_1;

assign grp_clock_cycle_fu_123_ap_start = grp_clock_cycle_fu_123_ap_start_reg;

assign hazard_dest_out = 32'd4294967295;

assign pc_out = PC_V;

assign reset_read_read_fu_80_p2 = reset;

assign stall_out = 1'd0;

endmodule //pipeline_top
