-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pipeline_top_clock_cycle is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    MEM_WB_valid_i : IN STD_LOGIC_VECTOR (0 downto 0);
    MEM_WB_valid_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    MEM_WB_valid_o_ap_vld : OUT STD_LOGIC;
    MEM_WB_dest_i : IN STD_LOGIC_VECTOR (1 downto 0);
    MEM_WB_dest_o : OUT STD_LOGIC_VECTOR (1 downto 0);
    MEM_WB_dest_o_ap_vld : OUT STD_LOGIC;
    MEM_WB_outVal_V_i : IN STD_LOGIC_VECTOR (0 downto 0);
    MEM_WB_outVal_V_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    MEM_WB_outVal_V_o_ap_vld : OUT STD_LOGIC;
    EX_MEM_valid_i : IN STD_LOGIC_VECTOR (0 downto 0);
    EX_MEM_valid_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    EX_MEM_valid_o_ap_vld : OUT STD_LOGIC;
    EX_MEM_dest_i : IN STD_LOGIC_VECTOR (1 downto 0);
    EX_MEM_dest_o : OUT STD_LOGIC_VECTOR (1 downto 0);
    EX_MEM_dest_o_ap_vld : OUT STD_LOGIC;
    EX_MEM_outVal_V_i : IN STD_LOGIC_VECTOR (0 downto 0);
    EX_MEM_outVal_V_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    EX_MEM_outVal_V_o_ap_vld : OUT STD_LOGIC;
    ID_EX_valid_i : IN STD_LOGIC_VECTOR (0 downto 0);
    ID_EX_valid_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    ID_EX_valid_o_ap_vld : OUT STD_LOGIC;
    ID_EX_src1_i : IN STD_LOGIC_VECTOR (1 downto 0);
    ID_EX_src1_o : OUT STD_LOGIC_VECTOR (1 downto 0);
    ID_EX_src1_o_ap_vld : OUT STD_LOGIC;
    ID_EX_src2_i : IN STD_LOGIC_VECTOR (1 downto 0);
    ID_EX_src2_o : OUT STD_LOGIC_VECTOR (1 downto 0);
    ID_EX_src2_o_ap_vld : OUT STD_LOGIC;
    ID_EX_dest_i : IN STD_LOGIC_VECTOR (1 downto 0);
    ID_EX_dest_o : OUT STD_LOGIC_VECTOR (1 downto 0);
    ID_EX_dest_o_ap_vld : OUT STD_LOGIC;
    PC_V_i : IN STD_LOGIC_VECTOR (31 downto 0);
    PC_V_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    PC_V_o_ap_vld : OUT STD_LOGIC;
    IF_ID_valid_i : IN STD_LOGIC_VECTOR (0 downto 0);
    IF_ID_valid_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    IF_ID_valid_o_ap_vld : OUT STD_LOGIC;
    IF_ID_pc_V_i : IN STD_LOGIC_VECTOR (31 downto 0);
    IF_ID_pc_V_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    IF_ID_pc_V_o_ap_vld : OUT STD_LOGIC;
    ID_EX_pc_V : OUT STD_LOGIC_VECTOR (31 downto 0);
    ID_EX_pc_V_ap_vld : OUT STD_LOGIC;
    ID_EX_val1_V : OUT STD_LOGIC_VECTOR (0 downto 0);
    ID_EX_val1_V_ap_vld : OUT STD_LOGIC;
    forward_B_sel_1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    forward_B_sel_1_ap_vld : OUT STD_LOGIC;
    forward_A_sel_1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    forward_A_sel_1_ap_vld : OUT STD_LOGIC );
end;


architecture behav of pipeline_top_clock_cycle is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal RegisterFile_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal RegisterFile_V_ce0 : STD_LOGIC;
    signal RegisterFile_V_we0 : STD_LOGIC;
    signal RegisterFile_V_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal IF_ID_valid_load_load_fu_235_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal IF_ID_valid_load_reg_567 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_forward_A_sel_1_new_4_phi_fu_81_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal ID_EX_valid_load_load_fu_197_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln65_2_fu_433_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_mux_forward_B_sel_1_new_1_phi_fu_91_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln65_4_fu_456_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_mux_storemerge18_phi_fu_102_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal storemerge18_reg_98 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_phi_mux_storemerge13_phi_fu_113_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge13_reg_109 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_storemerge9_phi_fu_125_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge9_reg_121 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln32_fu_168_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal wb_stage_instr_valid_load_fu_133_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln25_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln41_fu_495_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln291_fu_533_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sext_ln25_fu_141_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln25_fu_150_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln25_1_fu_156_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln25_1_fu_156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_fu_150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln32_fu_168_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln25_fu_141_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln69_fu_249_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_255_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln69_fu_265_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_1_fu_277_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln69_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_1_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln69_1_fu_283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_1_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_2_fu_303_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_fu_243_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_1_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_2_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln69_fu_289_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln65_3_fu_341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln37_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_4_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln65_fu_359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln65_1_fu_371_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln65_fu_365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln65_2_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_3_fu_383_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln65_fu_327_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln80_fu_397_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln80_fu_397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln76_fu_335_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln65_3_fu_409_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_5_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_4_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_6_fu_427_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln65_1_fu_389_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln80_fu_403_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln65_4_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln65_3_fu_442_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pipeline_top_clock_cycle_RegisterFile_V_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (0 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    RegisterFile_V_U : component pipeline_top_clock_cycle_RegisterFile_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 1,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => RegisterFile_V_address0,
        ce0 => RegisterFile_V_ce0,
        we0 => RegisterFile_V_we0,
        d0 => MEM_WB_outVal_V_i,
        q0 => RegisterFile_V_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    storemerge13_reg_109_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_lv1_0 = IF_ID_valid_load_load_fu_235_p1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                storemerge13_reg_109 <= ap_const_lv1_1;
            elsif (((ap_const_lv1_1 = IF_ID_valid_load_reg_567) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                storemerge13_reg_109 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    storemerge18_reg_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_lv1_0 = IF_ID_valid_load_load_fu_235_p1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                storemerge18_reg_98 <= ap_const_lv32_0;
            elsif (((ap_const_lv1_1 = IF_ID_valid_load_reg_567) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                storemerge18_reg_98 <= IF_ID_pc_V_i;
            end if; 
        end if;
    end process;

    storemerge9_reg_121_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_lv1_0 = IF_ID_valid_load_load_fu_235_p1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                storemerge9_reg_121 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = IF_ID_valid_load_reg_567) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                storemerge9_reg_121 <= RegisterFile_V_q0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                IF_ID_valid_load_reg_567 <= IF_ID_valid_i;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, IF_ID_valid_load_load_fu_235_p1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_lv1_0 = IF_ID_valid_load_load_fu_235_p1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif (((ap_const_lv1_1 = IF_ID_valid_load_load_fu_235_p1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;

    EX_MEM_dest_o_assign_proc : process(ap_CS_fsm_state1, EX_MEM_dest_i, ID_EX_dest_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            EX_MEM_dest_o <= ID_EX_dest_i;
        else 
            EX_MEM_dest_o <= EX_MEM_dest_i;
        end if; 
    end process;


    EX_MEM_dest_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            EX_MEM_dest_o_ap_vld <= ap_const_logic_1;
        else 
            EX_MEM_dest_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    EX_MEM_outVal_V_o_assign_proc : process(ap_CS_fsm_state1, EX_MEM_outVal_V_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            EX_MEM_outVal_V_o <= ap_const_lv1_0;
        else 
            EX_MEM_outVal_V_o <= EX_MEM_outVal_V_i;
        end if; 
    end process;


    EX_MEM_outVal_V_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            EX_MEM_outVal_V_o_ap_vld <= ap_const_logic_1;
        else 
            EX_MEM_outVal_V_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    EX_MEM_valid_o_assign_proc : process(ap_CS_fsm_state1, EX_MEM_valid_i, ID_EX_valid_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            EX_MEM_valid_o <= ID_EX_valid_i;
        else 
            EX_MEM_valid_o <= EX_MEM_valid_i;
        end if; 
    end process;


    EX_MEM_valid_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            EX_MEM_valid_o_ap_vld <= ap_const_logic_1;
        else 
            EX_MEM_valid_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    ID_EX_dest_o_assign_proc : process(ID_EX_dest_i, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ID_EX_dest_o <= ap_const_lv2_3;
        else 
            ID_EX_dest_o <= ID_EX_dest_i;
        end if; 
    end process;


    ID_EX_dest_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ID_EX_dest_o_ap_vld <= ap_const_logic_1;
        else 
            ID_EX_dest_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    ID_EX_pc_V <= ap_phi_mux_storemerge18_phi_fu_102_p4;

    ID_EX_pc_V_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ID_EX_pc_V_ap_vld <= ap_const_logic_1;
        else 
            ID_EX_pc_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    ID_EX_src1_o_assign_proc : process(ID_EX_src1_i, ap_CS_fsm_state3, select_ln41_fu_495_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ID_EX_src1_o <= select_ln41_fu_495_p3;
        else 
            ID_EX_src1_o <= ID_EX_src1_i;
        end if; 
    end process;


    ID_EX_src1_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ID_EX_src1_o_ap_vld <= ap_const_logic_1;
        else 
            ID_EX_src1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    ID_EX_src2_o_assign_proc : process(ID_EX_src2_i, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ID_EX_src2_o <= ap_const_lv2_3;
        else 
            ID_EX_src2_o <= ID_EX_src2_i;
        end if; 
    end process;


    ID_EX_src2_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ID_EX_src2_o_ap_vld <= ap_const_logic_1;
        else 
            ID_EX_src2_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    ID_EX_val1_V <= ap_phi_mux_storemerge9_phi_fu_125_p4;

    ID_EX_val1_V_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ID_EX_val1_V_ap_vld <= ap_const_logic_1;
        else 
            ID_EX_val1_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    ID_EX_valid_load_load_fu_197_p1 <= ID_EX_valid_i;

    ID_EX_valid_o_assign_proc : process(ap_CS_fsm_state1, ID_EX_valid_i, IF_ID_valid_load_load_fu_235_p1, IF_ID_valid_load_reg_567, ap_CS_fsm_state3)
    begin
        if (((ap_const_lv1_0 = IF_ID_valid_load_load_fu_235_p1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ID_EX_valid_o <= ap_const_lv1_0;
        elsif (((ap_const_lv1_1 = IF_ID_valid_load_reg_567) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ID_EX_valid_o <= ap_const_lv1_1;
        else 
            ID_EX_valid_o <= ID_EX_valid_i;
        end if; 
    end process;


    ID_EX_valid_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, IF_ID_valid_load_load_fu_235_p1, IF_ID_valid_load_reg_567, ap_CS_fsm_state3)
    begin
        if ((((ap_start = ap_const_logic_1) and (ap_const_lv1_0 = IF_ID_valid_load_load_fu_235_p1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv1_1 = IF_ID_valid_load_reg_567) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            ID_EX_valid_o_ap_vld <= ap_const_logic_1;
        else 
            ID_EX_valid_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    IF_ID_pc_V_o_assign_proc : process(PC_V_i, IF_ID_pc_V_i, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            IF_ID_pc_V_o <= PC_V_i;
        else 
            IF_ID_pc_V_o <= IF_ID_pc_V_i;
        end if; 
    end process;


    IF_ID_pc_V_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            IF_ID_pc_V_o_ap_vld <= ap_const_logic_1;
        else 
            IF_ID_pc_V_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    IF_ID_valid_load_load_fu_235_p1 <= IF_ID_valid_i;

    IF_ID_valid_o_assign_proc : process(IF_ID_valid_i, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            IF_ID_valid_o <= ap_const_lv1_1;
        else 
            IF_ID_valid_o <= IF_ID_valid_i;
        end if; 
    end process;


    IF_ID_valid_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            IF_ID_valid_o_ap_vld <= ap_const_logic_1;
        else 
            IF_ID_valid_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    MEM_WB_dest_o_assign_proc : process(ap_CS_fsm_state1, MEM_WB_dest_i, EX_MEM_dest_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            MEM_WB_dest_o <= EX_MEM_dest_i;
        else 
            MEM_WB_dest_o <= MEM_WB_dest_i;
        end if; 
    end process;


    MEM_WB_dest_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            MEM_WB_dest_o_ap_vld <= ap_const_logic_1;
        else 
            MEM_WB_dest_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    MEM_WB_outVal_V_o_assign_proc : process(ap_CS_fsm_state1, MEM_WB_outVal_V_i, EX_MEM_outVal_V_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            MEM_WB_outVal_V_o <= EX_MEM_outVal_V_i;
        else 
            MEM_WB_outVal_V_o <= MEM_WB_outVal_V_i;
        end if; 
    end process;


    MEM_WB_outVal_V_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            MEM_WB_outVal_V_o_ap_vld <= ap_const_logic_1;
        else 
            MEM_WB_outVal_V_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    MEM_WB_valid_o_assign_proc : process(ap_CS_fsm_state1, MEM_WB_valid_i, EX_MEM_valid_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            MEM_WB_valid_o <= EX_MEM_valid_i;
        else 
            MEM_WB_valid_o <= MEM_WB_valid_i;
        end if; 
    end process;


    MEM_WB_valid_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            MEM_WB_valid_o_ap_vld <= ap_const_logic_1;
        else 
            MEM_WB_valid_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    PC_V_o_assign_proc : process(PC_V_i, ap_CS_fsm_state3, add_ln291_fu_533_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            PC_V_o <= add_ln291_fu_533_p2;
        else 
            PC_V_o <= PC_V_i;
        end if; 
    end process;


    PC_V_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            PC_V_o_ap_vld <= ap_const_logic_1;
        else 
            PC_V_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    RegisterFile_V_address0_assign_proc : process(ap_CS_fsm_state1, sext_ln32_fu_168_p1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            RegisterFile_V_address0 <= ap_const_lv5_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            RegisterFile_V_address0 <= sext_ln32_fu_168_p1(5 - 1 downto 0);
        else 
            RegisterFile_V_address0 <= "XXXXX";
        end if; 
    end process;


    RegisterFile_V_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            RegisterFile_V_ce0 <= ap_const_logic_1;
        else 
            RegisterFile_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    RegisterFile_V_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, wb_stage_instr_valid_load_fu_133_p1, or_ln25_fu_162_p2)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (or_ln25_fu_162_p2 = ap_const_lv1_0) and (wb_stage_instr_valid_load_fu_133_p1 = ap_const_lv1_1))) then 
            RegisterFile_V_we0 <= ap_const_logic_1;
        else 
            RegisterFile_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln291_fu_533_p2 <= std_logic_vector(unsigned(PC_V_i) + unsigned(ap_const_lv32_4));
    add_ln69_fu_249_p2 <= std_logic_vector(signed(sext_ln25_fu_141_p1) + signed(ap_const_lv3_1));
    and_ln65_1_fu_315_p2 <= (icmp_ln65_fu_243_p2 and icmp_ln65_2_fu_303_p2);
    and_ln65_2_fu_321_p2 <= (and_ln65_fu_309_p2 and and_ln65_1_fu_315_p2);
    and_ln65_3_fu_383_p2 <= (xor_ln37_fu_353_p2 and or_ln65_2_fu_377_p2);
    and_ln65_4_fu_415_p2 <= (icmp_ln76_fu_335_p2 and icmp_ln65_2_fu_303_p2);
    and_ln65_5_fu_421_p2 <= (or_ln65_3_fu_409_p2 and icmp_ln65_1_fu_297_p2);
    and_ln65_6_fu_427_p2 <= (and_ln65_5_fu_421_p2 and and_ln65_4_fu_415_p2);
    and_ln65_fu_309_p2 <= (icmp_ln65_1_fu_297_p2 and EX_MEM_valid_i);
    and_ln69_1_fu_283_p2 <= (icmp_ln69_1_fu_277_p2 and and_ln69_fu_271_p2);
    and_ln69_fu_271_p2 <= (icmp_ln69_fu_265_p2 and MEM_WB_valid_i);
    and_ln80_fu_403_p2 <= (icmp_ln80_fu_397_p2 and and_ln69_fu_271_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_forward_A_sel_1_new_4_phi_fu_81_p4_assign_proc : process(ap_CS_fsm_state1, ID_EX_valid_load_load_fu_197_p1, select_ln65_2_fu_433_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
            if ((ap_const_lv1_1 = ID_EX_valid_load_load_fu_197_p1)) then 
                ap_phi_mux_forward_A_sel_1_new_4_phi_fu_81_p4 <= select_ln65_2_fu_433_p3;
            elsif ((ap_const_lv1_0 = ID_EX_valid_load_load_fu_197_p1)) then 
                ap_phi_mux_forward_A_sel_1_new_4_phi_fu_81_p4 <= ap_const_lv2_0;
            else 
                ap_phi_mux_forward_A_sel_1_new_4_phi_fu_81_p4 <= "XX";
            end if;
        else 
            ap_phi_mux_forward_A_sel_1_new_4_phi_fu_81_p4 <= "XX";
        end if; 
    end process;


    ap_phi_mux_forward_B_sel_1_new_1_phi_fu_91_p4_assign_proc : process(ap_CS_fsm_state1, ID_EX_valid_load_load_fu_197_p1, select_ln65_4_fu_456_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
            if ((ap_const_lv1_1 = ID_EX_valid_load_load_fu_197_p1)) then 
                ap_phi_mux_forward_B_sel_1_new_1_phi_fu_91_p4 <= select_ln65_4_fu_456_p3;
            elsif ((ap_const_lv1_0 = ID_EX_valid_load_load_fu_197_p1)) then 
                ap_phi_mux_forward_B_sel_1_new_1_phi_fu_91_p4 <= ap_const_lv2_0;
            else 
                ap_phi_mux_forward_B_sel_1_new_1_phi_fu_91_p4 <= "XX";
            end if;
        else 
            ap_phi_mux_forward_B_sel_1_new_1_phi_fu_91_p4 <= "XX";
        end if; 
    end process;


    ap_phi_mux_storemerge13_phi_fu_113_p4_assign_proc : process(IF_ID_valid_load_reg_567, ap_CS_fsm_state3, storemerge13_reg_109)
    begin
        if (((ap_const_lv1_1 = IF_ID_valid_load_reg_567) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_storemerge13_phi_fu_113_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_storemerge13_phi_fu_113_p4 <= storemerge13_reg_109;
        end if; 
    end process;


    ap_phi_mux_storemerge18_phi_fu_102_p4_assign_proc : process(IF_ID_pc_V_i, IF_ID_valid_load_reg_567, storemerge18_reg_98, ap_CS_fsm_state3)
    begin
        if (((ap_const_lv1_1 = IF_ID_valid_load_reg_567) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_storemerge18_phi_fu_102_p4 <= IF_ID_pc_V_i;
        else 
            ap_phi_mux_storemerge18_phi_fu_102_p4 <= storemerge18_reg_98;
        end if; 
    end process;


    ap_phi_mux_storemerge9_phi_fu_125_p4_assign_proc : process(RegisterFile_V_q0, IF_ID_valid_load_reg_567, ap_CS_fsm_state3, storemerge9_reg_121)
    begin
        if (((ap_const_lv1_1 = IF_ID_valid_load_reg_567) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_storemerge9_phi_fu_125_p4 <= RegisterFile_V_q0;
        else 
            ap_phi_mux_storemerge9_phi_fu_125_p4 <= storemerge9_reg_121;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    forward_A_sel_1 <= ap_phi_mux_forward_A_sel_1_new_4_phi_fu_81_p4;

    forward_A_sel_1_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            forward_A_sel_1_ap_vld <= ap_const_logic_1;
        else 
            forward_A_sel_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    forward_B_sel_1 <= ap_phi_mux_forward_B_sel_1_new_1_phi_fu_91_p4;

    forward_B_sel_1_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            forward_B_sel_1_ap_vld <= ap_const_logic_1;
        else 
            forward_B_sel_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln25_1_fu_156_p0 <= MEM_WB_dest_i;
    icmp_ln25_1_fu_156_p2 <= "1" when (icmp_ln25_1_fu_156_p0 = ap_const_lv2_0) else "0";
    icmp_ln25_fu_150_p0 <= MEM_WB_dest_i;
    icmp_ln25_fu_150_p2 <= "1" when (icmp_ln25_fu_150_p0 = ap_const_lv2_3) else "0";
    icmp_ln65_1_fu_297_p2 <= "0" when (EX_MEM_dest_i = ap_const_lv2_3) else "1";
    icmp_ln65_2_fu_303_p2 <= "0" when (EX_MEM_dest_i = ap_const_lv2_0) else "1";
    icmp_ln65_3_fu_341_p2 <= "1" when (EX_MEM_dest_i = ap_const_lv2_3) else "0";
    icmp_ln65_4_fu_347_p2 <= "1" when (EX_MEM_dest_i = ap_const_lv2_0) else "0";
    icmp_ln65_fu_243_p2 <= "1" when (EX_MEM_dest_i = ID_EX_src1_i) else "0";
    icmp_ln69_1_fu_277_p0 <= MEM_WB_dest_i;
    icmp_ln69_1_fu_277_p2 <= "1" when (icmp_ln69_1_fu_277_p0 = ID_EX_src1_i) else "0";
    icmp_ln69_fu_265_p2 <= "0" when (tmp_fu_255_p4 = ap_const_lv2_0) else "1";
    icmp_ln76_fu_335_p2 <= "1" when (EX_MEM_dest_i = ID_EX_src2_i) else "0";
    icmp_ln80_fu_397_p0 <= MEM_WB_dest_i;
    icmp_ln80_fu_397_p2 <= "1" when (icmp_ln80_fu_397_p0 = ID_EX_src2_i) else "0";
    or_ln25_fu_162_p2 <= (icmp_ln25_fu_150_p2 or icmp_ln25_1_fu_156_p2);
    or_ln65_1_fu_371_p2 <= (xor_ln65_fu_359_p2 or icmp_ln65_4_fu_347_p2);
    or_ln65_2_fu_377_p2 <= (or_ln65_fu_365_p2 or or_ln65_1_fu_371_p2);
    or_ln65_3_fu_409_p2 <= (and_ln65_2_fu_321_p2 or EX_MEM_valid_i);
    or_ln65_4_fu_450_p2 <= (and_ln80_fu_403_p2 or and_ln65_6_fu_427_p2);
    or_ln65_fu_365_p2 <= (xor_ln37_fu_353_p2 or icmp_ln65_3_fu_341_p2);
    select_ln41_fu_495_p3 <= 
        ap_const_lv2_3 when (ap_phi_mux_storemerge13_phi_fu_113_p4(0) = '1') else 
        ap_const_lv2_0;
    select_ln65_1_fu_389_p3 <= 
        select_ln69_fu_289_p3 when (and_ln65_3_fu_383_p2(0) = '1') else 
        select_ln65_fu_327_p3;
    select_ln65_2_fu_433_p3 <= 
        select_ln65_fu_327_p3 when (and_ln65_6_fu_427_p2(0) = '1') else 
        select_ln65_1_fu_389_p3;
    select_ln65_3_fu_442_p3 <= 
        ap_const_lv2_1 when (and_ln65_6_fu_427_p2(0) = '1') else 
        ap_const_lv2_2;
    select_ln65_4_fu_456_p3 <= 
        select_ln65_3_fu_442_p3 when (or_ln65_4_fu_450_p2(0) = '1') else 
        ap_const_lv2_0;
    select_ln65_fu_327_p3 <= 
        ap_const_lv2_1 when (and_ln65_2_fu_321_p2(0) = '1') else 
        select_ln69_fu_289_p3;
    select_ln69_fu_289_p3 <= 
        ap_const_lv2_2 when (and_ln69_1_fu_283_p2(0) = '1') else 
        ap_const_lv2_0;
    sext_ln25_fu_141_p0 <= MEM_WB_dest_i;
        sext_ln25_fu_141_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln25_fu_141_p0),3));

    sext_ln32_fu_168_p0 <= MEM_WB_dest_i;
        sext_ln32_fu_168_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln32_fu_168_p0),64));

    tmp_fu_255_p4 <= add_ln69_fu_249_p2(2 downto 1);
    wb_stage_instr_valid_load_fu_133_p1 <= MEM_WB_valid_i;
    xor_ln37_fu_353_p2 <= (ap_const_lv1_1 xor EX_MEM_valid_i);
    xor_ln65_fu_359_p2 <= (icmp_ln65_fu_243_p2 xor ap_const_lv1_1);
end behav;
